### ISSUE TITLE
Runtime Error while Using model

### ISSUE THREAD

**Issue by KevKurian** [anon294384/DiffuseIT#6]
/content/DiffuseIT2
Using device: cpu
Using cache found in /root/.cache/torch/hub/facebookresearch_dino_main
Start iterations 0
  0% 0/120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/DiffuseIT2/main.py", line 8, in <module>
    image_editor.edit_image_by_prompt()
  File "/content/DiffuseIT2/optimization/image_editor.py", line 287, in edit_image_by_prompt
    for j, sample in enumerate(samples):
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 542, in p_sample_loop_progressive
    out = self.p_sample(
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 386, in p_sample
    out = self.p_mean_variance(
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/respace.py", line 91, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 240, in p_mean_variance
    model_output = model(x, self._scale_timesteps(t), **model_kwargs)
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/unet.py", line 656, in forward
    h = module(h, emb)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/DiffuseIT2/guided_diffusion/guided_diffusion/unet.py", line 77, in forward
    x = layer(x)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by cyclomon** [comment]
Hi, the pre-trained models of DINO ViT does not provide running on CPU.
Please use cuda GPU for running the script.

Thanks
